import Head from "next/head";

// COMPONENTS
import Navbar from "@/components/molecules/index-page/Navbar";
import Hero from "@/components/molecules/index-page/Hero";
import NewDrops from "@/components/molecules/index-page/NewDrops";
import Category from "@/components/molecules/index-page/Category";
export default function Home() {
	return (
		<>
			<Head>
				<title>Kicks</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>
			<main className="bg-lightGray">
				<section className="px-4 py-6">
					<Navbar />
					<Hero />
					<NewDrops />
				</section>
				<section>
					<Category />
				</section>
			</main>
		</>
	);
}
