import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>Kicks</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>
			<main className="">
				<h1 className="text-3xl text-mainBlue font-bold underline font-rubikFont">
					Hello world!
				</h1>
				<p className=" text-6xl font-rubikFont text-mainYellow">
					holla World
				</p>
			</main>
		</>
	);
}
