
// COMPONENTS
import Hero from "@/components/molecules/index-page/Hero";
import NewDrops from "@/components/molecules/index-page/NewDrops";
import Category from "@/components/molecules/index-page/Category";
import Reviews from "@/components/molecules/index-page/Reviews";
import Head from "next/head";

//--------------------------
export default function Home() {
	return (
		<>
			<Head>
				<title>Kicks</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>
			<main>
				<section className="px-4 pb-8 lg:px-10 lg:pb-8">
					<Hero />
					<NewDrops />
				</section>
				<section>
					<Category />
				</section>
				<section className="p-4 lg:px-10">
					<Reviews />
				</section>
			</main>
		</>
	);
}
